import Head from 'next/head'
import React from 'react'
import Navbar from './Navbar'

type Props = {
  children?: React.ReactNode
}

const Layout = ({children}: Props) => {
  return (
    <>
      <Head>
        <title>Workout Tracking App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className="flex min-h-screen flex-col items-center bg-slate-800">
        {children}
      </main>
    </>
  )
}

export default Layout